### ISSUE TITLE
Unable to use, no icon

### ISSUE THREAD

**Issue by jasonkaisersmith** [Cmyna/AreaBucket#1]
No icon appears and I am unable to use the mod.
It is listed in the "options", so appears to have loaded OK.  But not usable.

Also, it would in general be helpful to have a video to show how to use the mode.

And as a final note.  The link for discord also appear not to work I get a message that I have "no access to text channels!".

**Comment by screenarzzz** [comment]
Same here, mod seems to be installed, but there is no additional icon in my toolbar yet.

**Comment by Cmyna** [comment]
Hello, thanks for your reminder, so that I can realized I put the wrong discord link. I have updated the discord link, or you can just access this - https://discord.gg/JS5upVUmrY. The text channel for is mod is under mods-wip, and you can discover simple demo video I posted there.
And the tool of this mod (currently) can be active (and tool options shown) only if you pick up any surface assets. like selecting any surfaces in Extra Detailings tool/Find it mods panel, or even pick a surface asset in vanilla developer assets panel.
